[project]
name = "flaskr"
version = "1.0.0"
description = "The basic Todo app built in the Flask tutorial. Inspired from palletprojects blog app"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"